<?php

// user status types
define('USER_STATUS', 'USER_STATUS');

// User Status Values
define('USER_STATUS_ACTIVE', 'ACTIVE');
define('USER_STATUS_INACTIVE', 'INACTIVE');
define('USER_STATUS_PENDING_VERIFICATION', 'PENDING_VERIFICATION');
define('USER_STATUS_SUSPENDED', 'SUSPENDED');
define('USER_STATUS_LOCKED', 'LOCKED');

// Generic Status
define('GENERIC_STATUS', 'GENERIC_STATUS');

define('LOOKUP_VALUE_STATUS', 'LOOKUP_VALUE_STATUS');

define('LOOKUP_VALUE_STATUS_PENDING', 'PENDING');
define('LOOKUP_VALUE_STATUS_ACCEPT_FOR_ALL', 'ACCEPT_FOR_ALL');
define('LOOKUP_VALUE_STATUS_ACCEPT_FOR_THIS', 'ACCEPT_FOR_THIS');
define('LOOKUP_VALUE_STATUS_REJECT', 'REJECT');
