<?php

return [

    NOTIFICATION_TEMPLATE_KEY_USER_REGISTRATION => [
        NOTIFICATION_TEMPLATE_REQUIRED_DATA_KEY => ['name', 'full_name', 'email', 'password'],
        ENGLISH_LANG_KEY => [
            NOTIFICATION_TEMPLATE_EMAIL_KEY => NOTIFICATION_TEMPLATE_NAME_USER_REGISTRATION_EN,
            NOTIFICATION_TEMPLATE_SMS_KEY => NOTIFICATION_TEMPLATE_NAME_USER_REGISTRATION_EN,
        ],
        AMHARIC_LANG_KEY => [
            NOTIFICATION_TEMPLATE_EMAIL_KEY => NOTIFICATION_TEMPLATE_NAME_USER_REGISTRATION_AM,
            NOTIFICATION_TEMPLATE_SMS_KEY => NOTIFICATION_TEMPLATE_NAME_USER_REGISTRATION_AM,
        ],
    ],

    NOTIFICATION_TEMPLATE_KEY_OTP => [
        NOTIFICATION_TEMPLATE_REQUIRED_DATA_KEY => ['name', 'otp', 'message', 'time'],
        ENGLISH_LANG_KEY => [
            NOTIFICATION_TEMPLATE_EMAIL_KEY => NOTIFICATION_TEMPLATE_NAME_OTP_EN,
            NOTIFICATION_TEMPLATE_SMS_KEY => NOTIFICATION_TEMPLATE_NAME_OTP_EN,
        ],
        AMHARIC_LANG_KEY => [
            NOTIFICATION_TEMPLATE_EMAIL_KEY => NOTIFICATION_TEMPLATE_NAME_OTP_AM,
            NOTIFICATION_TEMPLATE_SMS_KEY => NOTIFICATION_TEMPLATE_NAME_OTP_AM,
        ],
    ],

];
